spring:
  jackson:
    time-zone: "America/Los_Angeles"
    date-format: "yyyy-MM-dd"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:h2:mem:testData;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    format_sql: true
    generate-ddl: true
    database-platform: H2
    properties:
      hibernate:
        show_sql: true
        format_sql: true
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml
  url: jdbc:h2:mem:testData
  user: sa
  password:
management:
  security:
    enabled: false
logging:
  level:
    org:
      hibernate:
        type: trace